### ISSUE TITLE
SSL: WRONG_VERSION_NUMBER Error When Sending Messages

### ISSUE THREAD

**Issue by TheHollidayInn** [shughes-uk/python-youtubechat#2]
```
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/keithholliday/Documents/Code/Python/twitchtube/pyoutubechat/youtubechat/ytchat.py", line 163, in run
    pageToken=self.livechatIds[chat_id]['pageToken'])
  File "/Users/keithholliday/Documents/Code/Python/twitchtube/pyoutubechat/youtubechat/ytchat.py", line 292, in live_chat_messages_list
    resp, content = self.http.request(url, 'GET')
  File "/Library/Python/2.7/site-packages/oauth2client/client.py", line 596, in new_request
    redirections, connection_type)
  File "/Library/Python/2.7/site-packages/httplib2/__init__.py", line 1609, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/Library/Python/2.7/site-packages/httplib2/__init__.py", line 1351, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/Library/Python/2.7/site-packages/httplib2/__init__.py", line 1307, in _conn_request
    response = conn.getresponse()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1132, in getresponse
    response.begin()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 734, in recv
    return self.read(buflen)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 621, in read
    v = self._sslobj.read(len or 1024)
SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1752)
```

When sending messages, sometimes I get the following error and some other SSL errors. I'm happy to supply any code to help if needed.

**Comment by TheHollidayInn** [comment]
I figured out that the issue was that I was calling send_message outside of the subscribed method on the same thread as the subscribed method.

**Comment by shughes-uk** [comment]
Glad you worked it out. Lemme know if you find any other issues, keen to hear about them!
