### ISSUE TITLE
Getting clientsecrets.py Error 

### ISSUE THREAD

**Issue by SiirRandall** [shughes-uk/python-youtubechat#7]
When trying to run the get_oauth_token.py I get this error.

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/oauth2client/clientsecrets.py", line 121, in _loadfile
    with open(filename, 'r') as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'client_secrets.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "get_oauth_token.py", line 14, in <module>
    redirect_uri='urn:ietf:wg:oauth:2.0:oob')
  File "/home/pi/.local/lib/python3.5/site-packages/oauth2client/_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/pi/.local/lib/python3.5/site-packages/oauth2client/client.py", line 2135, in flow_from_clientsecrets
    cache=cache)
  File "/home/pi/.local/lib/python3.5/site-packages/oauth2client/clientsecrets.py", line 165, in loadfile
    return _loadfile(filename)
  File "/home/pi/.local/lib/python3.5/site-packages/oauth2client/clientsecrets.py", line 125, in _loadfile
    exc.strerror, exc.errno)
oauth2client.clientsecrets.InvalidClientSecretsError: ('Error opening file', 'client_secrets.json', 'No such file or directory', 2)

I ran this on my pi and macbook both come back with this error.

**Comment by SiirRandall** [comment]
Never mind I was being stupid here. I apologize for this issue. For some reason I thought it would make the file for me. I went to the dev portal on google and got the right file. Still new to python again I apologize for this.

**Comment by bigsby-exe** [comment]
for anyone running into this issue in the future check here for info:
https://developers.google.com/youtube/v3/quickstart/python
